### ISSUE TITLE
 HelixFold3代码存在各种bug

### ISSUE THREAD

**Issue by Maikuraky** [PaddlePaddle/PaddleHelix#313]

**Comment by xiaoyao4573** [comment]
感谢您对我们工作的及时关住。我们团队在A100上测试能够正常使用，但由于机器和环境等因素可能导致您使用不畅，我们会持续进行优化。欢迎给我们反馈具体的问题，方便我们解决。

**Comment by RyanGarciaLI** [comment]
您好，很高兴您对我们工作的关注，我们自己内部测试能够正常使用。但考虑到机器和环境等因素，可能有覆盖不全的地方。请耐心反馈一下具体问题，我们好查看修正。我们一直在提升代码，以便更好地提供服务。谢谢～

Dear, we greatly appreciate your interest in our work. HelixFold3 has passed all our tests. However, due to the different settings of machines or environments, we may not be able to cover all the corner cases. Please specify the problems you are stuck in. We are keen on improving our model to provide better community service. Thank you.

**Comment by Maikuraky** [comment]
查看下7qr4的demo，用你们提供的run_infer.sh脚本试试

**Comment by RyanGarciaLI** [comment]
`/data/demo_7qr4.json` 已经被废弃，但是个不错的case，让我们发现的代码里的bug。问题是 `run_infer.sh` 中遗漏了`--nhmmer_binary_path` 变量导致搜索RNA MSA时找不到库而报错，最新的提交中我们补上了相应的变量，通过了自测。您可以重新来最新的`run_infer.sh` 或者直接在`run_infer.sh`添加
```bash
        --nhmmer_binary_path "$ENV_BIN/nhmmer"
```

`/data/demo_7qr4.json` has been obsoleted. But that is a good case to help us discover a bug in our code. The problem is an environment variable named "--nhmmer_binary_path" is missing in `run_infer.sh`. The model can't use this library to search RNA MSA and raise an MSA missing error. We have fixed this problem in our latest commit and passed our test. You can pull the latest `run_infer.sh` or just add a line in `run_infer.sh` as follows, 
```bash
        --nhmmer_binary_path "$ENV_BIN/nhmmer"
```
