### ISSUE TITLE
helixfold3 runs out of memory

### ISSUE THREAD

**Issue by Garhorne0813** [PaddlePaddle/PaddleHelix#336]
Hello! Great work!

When I used `run_infer.sh` to process a protein pentamer on an A100 40G GPU, the memory ran out, regardless of whether I used FP32 or BF16. Is there a way to resolve this issue?

Thank you!

```
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 4.959646GB memory on GPU 0, 36.089233GB memory has been allocated and available memory is only 3.304626GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
 (at ../paddle/fluid/memory/allocation/cuda_allocator.cc:73)
```

**Comment by RyanGarciaLI** [comment]
Hi,

We greatly appreciate your interest in our work. How many tokens does your protein pentamer have? As mentioned in our [README - Resource Usage](https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/protein_folding/helixfold3#resource-usage) Section, 
> The maximum number of tokens is around 1200 for inference on a single A100-40G GPU with precision bf16.
The current model may not support the protein with more than 1200 tokens. Otherwise, you may look for larger GPU memory.

Another way to work around it is to reduce `subbatch_size` and `num_recycle` to save GPU memory. See [README - Resource Usage](https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/protein_folding/helixfold3#resource-usage) Section for more details. Note that smaller `subbatch_size` leads to slower inference, and reducing `num_recycle` may downgrade model accuracy. 

Btw you can also try it on our online server: https://paddlehelix.baidu.com/app/all/helixfold3/forecast

**Comment by Garhorne0813** [comment]
Thank you for your reply!

I'm curious if it's possible to use multiple GPUs to solve this issue.

**Comment by RyanGarciaLI** [comment]
Unfortunately, our official open-source model doesn't support multiple GPU inference.
