### ISSUE TITLE
No module named 'pgl.graph_wrapper'

### ISSUE THREAD

**Issue by masapasa** [PaddlePaddle/PaddleHelix#69]
Is it deprecated? Do we need to upgrade to pgl.graph?

**Comment by Noisyntrain** [comment]
Hi, since the pgl has a large api change from verisoin 1.2.1 to 2.1, the original GraphWrapper is deprecated. We are still in the process of modifying and testing code to make our project compatible with pgl 2.x version. 
For now, if you want to run our code, you can install the pgl of version 1.2.1. To be more specific:
```
#uninstall pgl 2.1
python -m pip uninstall pgl
#install pgl 1.2.1
python -m pip install pgl==1.2.1
```
Hope this can be helpful to you. :)
